function manageException(e) {
    console.error('Error:', e.message);
}

export { manageException };